# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d849748f19654cbc47dc31319de506824968f01e0d240caa897f34051f9f0a6533f375146e0c9fcf6aa972398c50bb6820a015b6ab771ad88c5bfac8653b4419

test:
  secret_key_base: 125b158fb510aba71c3df5bc50e757763ae12f7a53e1c3683108e179879d78f6664ad4add4caec3c15f7dc6568fe8df9730839d016a07da5290ce4fe9006f694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
